### ISSUE TITLE
Seek not working on Android Chrome

### ISSUE THREAD

**Issue by bgazzera** [Uplynk/uplynkhtml5playersdk#2]
Hey @cspencer404 
We are experiencing an issue with Uplynk player v02.00.18012300, were the user
is not allowed to click on the timeline to scrub forward/backward.
 
OS: Android 6.0/7.0 (also on other versions)
Browser: Chrome mobile
 
Steps to reproduce:
Install locally the example player https://github.com/Uplynk/Sample-Players/blob/master/html5player/index.html
Open the index.html in Mobile Chrome in Android
Attempt to click on the timeline to fast-forward the media, or drag the
playhead.
 
Expected result:
The media should skip forward to the point clicked in the timeline
 
Actual result:
Media keeps on playing in the current time.
 
Note: If the user double-taps the timeline, media IS fast-forwarded to the
selected point in time. But single tap/drag do not work as expected.
Also, seek is working OK in iOS10

Please let me know if you need further information.

**Comment by cspencer404** [comment]
Thanks for reporting the problem. We have confirmed the issue, and will try to fix it.

**Comment by bgazzera** [comment]
Thanks for answering @cspencer404 !

Dunno if this helps but we have tried to debug the issue, trying different versions of plyr, in isolation. 
Seek works in plyr 2.0.9 there, so I guess it is something in the code wrapping plyr. 

Wish we could be more helpful, we'll keep on looking

**Comment by cspencer404** [comment]
This is fixed in version 02.00.18032700, now released.
