### ISSUE TITLE
Removal of plyr.js - can it be reconsidered?

### ISSUE THREAD

**Issue by kmcclosk** [Uplynk/uplynkhtml5playersdk#3]
The version of plyr used in this repo is a customization of https://plyr.io/. Because it is custom, having the custom version in un-minified form is very important for diagnosing the behavior of the overall system and saves a great deal of developer time when issues arise.

**Comment by cspencer404** [comment]
Yes, we can do that.

The reason I deleted it was that it wasn't being updated by our build process, so I've made the changes to that process so that the non-min'd files will also be published.

We should have a new release published today.
